#PBS -l select=1:ncpus=32:mem=64gb
#PBS -l walltime=23:55:00
#PBS -q pqberloff

module load gcc/11.2.0


cp $HOME/work/clustering/parameters.f90 $TMPDIR/parameters.f90
cp $HOME/work/clustering/constantsbeta32.f90 $TMPDIR/constants.f90
cp $HOME/work/clustering/rossby_wave_attributes.f90 $TMPDIR
cp $HOME/work/clustering/rossby_wave.f90 $TMPDIR
cp $HOME/work/clustering/admin.f90 $TMPDIR
cp $HOME/work/clustering/random.f90 $TMPDIR
cp $HOME/work/clustering/velocitywhole.f90 $TMPDIR/velocity.f90
cp $HOME/work/clustering/particle.f90 $TMPDIR
cp $HOME/work/clustering/passivetracersfixedpointtracer.f90 $TMPDIR/passivetracers.f90
cp $HOME/work/clustering/executedata.f90 $TMPDIR/executearray.f90

gfortran -c constants.f90
gfortran -c parameters.f90
gfortran -c admin.f90
gfortran -c random.f90
gfortran -c rossby_wave_attributes.f90
gfortran -c rossby_wave.f90
gfortran -fopenmp velocity.f90 -c
gfortran -fopenmp particle.f90 -c
gfortran -fopenmp passivetracers.f90 -c
gfortran -fopenmp executearray.f90 -c
gfortran -fopenmp constants.o parameters.o rossby_wave_attributes.o rossby_wave.o admin.o random.o velocity.o particle.o passivetracers.o executearray.o -o executearray
OMP_NUM_THREADS=32 ./executearray

cp partx.dat $HOME/work/partfiles/testvelocity/pavel/g01d01
cp party.dat $HOME/work/partfiles/testvelocity/pavel/g01d01
cp partavg.dat $HOME/work/partfiles/testvelocity/pavel/g01d01
cp fixedpoint.dat $HOME/work/partfiles/testvelocity/pavel/g01d01
cp counters.dat $HOME/work/partfiles/testvelocity/pavel/g01d01
cp uvel.dat $HOME/work/partfiles/testvelocity/pavel/g01d01
cp vvel.dat $HOME/work/partfiles/testvelocity/pavel/g01d01
cp bothvel.dat $HOME/work/partfiles/testvelocity/pavel/g01d01




