#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=23:55:00


module load anaconda3/personal


cp $HOME/work/clustering/plotimshowandparticle.py $TMPDIR

cp $HOME/work/partfiles/testvelocity/pavel/g01d01/partx.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g01d01/party.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g01d01/partavg.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g01d01/counters.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g01d01/fixedpoint.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g01d01/bothvel.dat $TMPDIR/fixed.dat




python plotimshowandparticle.py

cp anim.mp4 $HOME/work/clustering/imshowpavelg01d01.mp4


