#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=23:55:00


module load anaconda3/personal


cp $HOME/work/clustering/plotimshowandparticle.py $TMPDIR

cp $HOME/work/partfiles/testvelocity/pavel/g1d1/partx.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g1d1/party.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g1d1/partavg.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g1d1/counters.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g1d1/fixedpoint.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/g1d1/bothvel.dat $TMPDIR/fixed.dat




python plotimshowandparticle.py

cp anim.mp4 $HOME/work/clustering/imshowpavelg1d1.mp4


