#PBS -l select=1:ncpus=32:mem=64gb
#PBS -l walltime=23:55:00
#PBS -q pqberloff

module load anaconda3/personal


cp $HOME/work/clustering/plotparticle.py $TMPDIR
cp $HOME/work/partfiles/bigcluster/gamma01_250kparticles/delta1/partx.dat $TMPDIR
cp $HOME/work/partfiles/bigcluster/gamma01_250kparticles/delta1/party.dat $TMPDIR

python plotparticle.py

cp anim.mp4 $HOME/work/clustering/gamma01delta1.mp4
