#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=23:55:00


module load anaconda3/personal


cp $HOME/work/clustering/plotfixed.py $TMPDIR

cp $HOME/work/partfiles/testvelocity/test/partx.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/test/party.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/test/partavg.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/test/counters.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/test/fixedpoint.dat $TMPDIR





python plotfixed.py

cp anim.mp4 $HOME/work/clustering/fixedpoint.mp4


