#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=23:55:00


module load anaconda3/personal


cp $HOME/work/clustering/plotfixed.py $TMPDIR

cp $HOME/work/partfiles/testvelocity/testfine/smalln/partx.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/testfine/smalln/party.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/testfine/smalln/partavg.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/testfine/smalln/counters.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/testfine/smalln/fixedpoint.dat $TMPDIR





python plotfixed.py

cp anim.mp4 $HOME/work/clustering/fixedpointg1d1.mp4


