#PBS -l select=1:ncpus=256:mem=64gb
#PBS -l walltime=71:55:00


module load gcc/11.2.0


cp $HOME/work/clustering/parameters.f90 $TMPDIR/parameters.f90
cp $HOME/work/clustering/constantsbeta32.f90 $TMPDIR/constants.f90
cp $HOME/work/clustering/rossby_wave_attributes.f90 $TMPDIR
cp $HOME/work/clustering/rossby_wave.f90 $TMPDIR
cp $HOME/work/clustering/admin.f90 $TMPDIR
cp $HOME/work/clustering/random.f90 $TMPDIR
cp $HOME/work/clustering/velocitywhole.f90 $TMPDIR/velocity.f90
cp $HOME/work/clustering/particle.f90 $TMPDIR
cp $HOME/work/clustering/passivetracersstreampotential.f90 $TMPDIR/passivetracers.f90
cp $HOME/work/clustering/executedata.f90 $TMPDIR/executearray.f90

gfortran -c constants.f90
gfortran -c parameters.f90
gfortran -c admin.f90
gfortran -c random.f90
gfortran -c rossby_wave_attributes.f90
gfortran -c rossby_wave.f90
gfortran -fopenmp velocity.f90 -c
gfortran -fopenmp particle.f90 -c
gfortran -fopenmp passivetracers.f90 -c
gfortran -fopenmp executearray.f90 -c
gfortran -fopenmp constants.o parameters.o rossby_wave_attributes.o rossby_wave.o admin.o random.o velocity.o particle.o passivetracers.o executearray.o -o executearray
OMP_NUM_THREADS=256 ./executearray

cp partx.dat $HOME/work/partfiles/bigcluster/g01d01
cp party.dat $HOME/work/partfiles/bigcluster/g01d01
cp partavg.dat $HOME/work/partfiles/bigcluster/g01d01
cp stream.dat $HOME/work/partfiles/bigcluster/g01d01
cp pot.dat $HOME/work/partfiles/bigcluster/g01d01

cp stream.dat $HOME/work/clustering/streamdata/str.dat
cp pot.dat $HOME/work/clustering/streamdata/p.dat




