#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=23:55:00
#PBS -q pqberloff

module load anaconda3/personal


cp $HOME/work/clustering/fpfind/fixedpointnoanim.py $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/stream.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/pot.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/partx.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/party.dat $TMPDIR



python fixedpointnoanim.py

#cp anim.mp4 $HOME/work/clustering/fpfind

