#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=23:55:00
#PBS -q pqberloff

module load anaconda3/personal


cp $HOME/work/clustering/fpfind/fixedpointpot.py $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/smalltest/stream.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/smalltest/pot.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/smalltest/partx.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/smalltest/party.dat $TMPDIR



python fixedpointpot.py

cp anim.mp4 $HOME/work/clustering/fpfind

