#PBS -l select=1:ncpus=32:mem=64gb
#PBS -l walltime=23:55:00
#PBS -q pqberloff

module load anaconda3/personal


cp $HOME/work/clustering/fpfind/fixedparallel.py $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/smalltest0101/stream.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/smalltest0101/pot.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/smalltest0101/partx.dat $TMPDIR
cp $HOME/work/partfiles/testvelocity/pavel/data/smalltest0101/party.dat $TMPDIR


python fixedparallel.py

cp anim.mp4 $HOME/work/clustering/fpfind/anim0101allparallel.mp4

